Move GRUB install to a separate function

diff --git a/linstaller-backend b/linstaller-backend
--- a/linstaller-backend
+++ b/linstaller-backend
@@ -5,6 +5,27 @@
 function log() {
   echo "${1}" > "${MESSAGE_FILE}"
 }
+
+function install_grub() {
+  if [ -d "/sys/firmware/efi" ]; then
+    mkdir -p /target/efi
+    mount -o rw "${efi_partition}" /target/efi
+    chroot /target grub-install --force --removable --efi-directory=/efi --bootloader-id=GRUB "${target_disk}" || {
+      log "Fail when installing GRUB on ${target_partition}"
+      exit 4
+    }
+  else
+    chroot /target grub-install --force "${target_disk}" || {
+      log "Fail when installing GRUB on ${target_partition}"
+      exit 4
+    }
+  fi
+  
+  chroot /target update-grub || {
+      log "Fail when updating GRUB on ${target_partition}"
+      exit 5
+  }
+}
  
 function install_system() {
   log "Mounting /target..."
@@ -42,24 +63,7 @@ function install_system() {
   mount -o bind /dev  /target/dev
   mkdir -p /target/tmp
   
-  if [ -d "/sys/firmware/efi" ]; then
-    mkdir -p /target/efi
-    mount -o rw "${efi_partition}" /target/efi
-    chroot /target grub-install --force --removable --efi-directory=/efi --bootloader-id=GRUB "${target_disk}" || {
-      log "Fail when installing GRUB on ${target_partition}"
-      exit 4
-    }
-  else
-    chroot /target grub-install --force "${target_disk}" || {
-      log "Fail when installing GRUB on ${target_partition}"
-      exit 4
-    }
-  fi
-  
-  chroot /target update-grub || {
-      log "Fail when updating GRUB on ${target_partition}"
-      exit 5
-  }
+  install_grub
   
   # HOTFIX: update-grub taking wrong UUID of root partition
   #(
@@ -68,6 +72,8 @@ function install_system() {
     correct_uuid=$(blkid -o value -s UUID "${target_partition}")
     
     sed -i "s|${wrong_uuid}|${correct_uuid}|g" "grub.cfg"
+    
+    install_grub
   #)
  
   log "Setting up language..."
